#include "Header.idl"

module sensor_msgs {
  module msg {
    module dds_ {
        @final
        struct JointState_ {
            std_msgs::msg::dds_::Header_ header;

            sequence<string> name;

            sequence<double> position;

            sequence<double> velocity;

            sequence<double> effort;
        };
    };
  };
};
